site_name: plkit
theme:
    name: 'material'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'Configurations': 'configurations.md'
    - 'DataModule': 'datamodule.md'
    - 'Module': 'module.md'
    - 'Trainer': 'trainer.md'
    - 'Runner': 'runner.md'
    - 'Optuna integration': 'optuna.md'
    - 'API': mkapi/api/plkit
