
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='plkit',
    version='0.0.9',
    description='A wrapper for pytorch-lightning to make you write even less code',
    python_requires='==3.*,>=3.6.0',
    project_urls={"homepage": "https://github.com/pwwang/plkit", "repository": "https://github.com/pwwang/plkit"},
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    packages=['plkit'],
    package_dir={"": "."},
    package_data={"plkit": ["*.bak"]},
    install_requires=['cmdy', 'diot', 'optuna==2.*', 'pytorch-lightning', 'rich==8.*', 'torch==1.*', 'tqdm==4.48.0'],
    extras_require={"dev": ["numpy", "pytest", "pytest-cov", "torchvision"]},
)
